blank_issues_enabled: true
contact_links:
  - name: CFP
    url: SUBMIT.md
    about: Submit your CFP here
  - name: MongoDB Community
    url: https://www.mongodb.com/community
    about: Please ask and answer questions here.
